### ISSUE TITLE
Locations other than _data/

### ISSUE THREAD

**Issue by pedromorgan** [rosscdh/mkdocs-markdownextradata-plugin#13]
Am creating a site which has json files in sub directories.. which contains the "data" already..

eg https://welsh-railways.gitlab.io/station/foobar/meta.json

Is there a way to access that without creating symlinks to the `_data` directory ?

**Comment by rosscdh** [comment]
Hey there, yes as per https://github.com/rosscdh/mkdocs-markdownextradata-plugin#using-external-data-files

tho it assumes only 1 path

**Comment by pedromorgan** [comment]
umm that kinda not gonna work either I think..
Its the way am doing atmo, but with symlinks..

Ideally what would be perfect is from data in fm eg

```
---
title: More Data
xdata:
  - foo.json
  - bar: more_data.yml
---     
```
and in templates
```
<ul>
{% for rec in page.meta.xdata.foo %}
<li><a href="{{rec.path}}">{{rec.title}}</a></li>
{% endfor %}
</ul>
{{page.meta.xdata.bar.x}}
```

**Comment by rosscdh** [comment]
Sorry, wont change

**Comment by rosscdh** [comment]
Please check the 0.1.3 release for ability to handle multiple data locations
