### ISSUE TITLE
json booleans are translated into python booleans

### ISSUE THREAD

**Issue by peterw-ibm** [rosscdh/mkdocs-markdownextradata-plugin#16]
When injecting a json file with a json boolean (true, false), in the html javascript this boolean shows up as a python boolean (True, False), causing javscript to fail.

**Comment by rosscdh** [comment]
please provide your setup

**Comment by peterw-ibm** [comment]
Hope this helps.

folder setup:
- mkdocs.yml
- docs
  - index.md
  - json
    - test.json

-- mkdocs.yml ----------------------------
site_name: Test markdownextradata booleans
remote_branch: gh-pages
remote_name: origin
docs_dir: docs
markdown_extensions:
    - pymdownx.tilde
plugins:
    - search
    - markdownextradata:
        data: docs/json

-- index.md ---------------------
# Test markdownextradata booleans

<script>
    var test = {{ test }};
    console.log(`test = ${JSON.stringify(test, null, 4)}`);
</script>

-- test.json -------------------------------------
{
    "some_string": "hello",
    "bool_false": false,
    "bool_true": true
}

-- Browser console ----------------------------------
ReferenceError: False is not defined127.0.0.1:8000:66:41

-- Browser debugger --------------------------------
<h1 id="test-markdownextradata-booleans">Test markdownextradata booleans</h1>
<script>
    var test = {'some_string': 'hello', 'bool_false': False, 'bool_true': True};
    console.log(`test = ${JSON.stringify(test, null, 4)}`);
</script>

**Comment by rosscdh** [comment]
Yep, as noted in my previous comment; the purpose of this plugin is to provide variables to be used in your templates; not json strings "as" variables.

try the previously mentioned possiblity

```
my_variables:
  name: blah
  example_json: |-
   {"name": "bob"}
```
that "might" work. but currently this is a feature thats out of scope if not; if I get some time I may fix it but right now its OOS sorry. But feel free to make a PR.

**Comment by rosscdh** [comment]
So as promised (because im a sucker at 23:21) https://pypi.org/project/mkdocs-markdownextradata-plugin/0.1.5/

I have proven that the suggestion above works

you can see the test here: https://github.com/rosscdh/mkdocs-markdownextradata-plugin/blob/master/test/test_basic.py#L28
