### ISSUE TITLE
markdownextradata + markdown_include = not working :)

### ISSUE THREAD

**Issue by Tonic8** [rosscdh/mkdocs-markdownextradata-plugin#18]
Hello

Many thanks for your plugin!

On my last project, i'm using your plugin to insert automaticaly specific icons inside md file:

`this is a test and to show we can put 2 {{ star }}`

where 

```
extra:
    star:       "![star](ressources/star.png)"

```

and that work perfectly.

In this project i need to "include md file inside the main md file, for now i'm trying to use markdown_include 

unfortunately , it seems the md included (that contain the same kind of variable {{star}}), in the final document it is not rendered.

- here an example of inluded md file

```
### included md file

Inside the included md file there 3 {{ star}}
```

- here the main md file (with the included file and some star

```
# This is a test
{{star}}
---
{!test.md!}
---
{{star}}
```

as in the below screenshot, there is the star rendered in the main but not the one in the included file

![result](https://user-images.githubusercontent.com/18634390/81410573-4123fa00-9141-11ea-90c5-d2a41b068807.png)

I know there is 2 plugin involved and i think it depends of the order of execution. if you know another plugin allowing the inclusion and that work with yours, tha could be very cool!

**Comment by rosscdh** [comment]
Hi there, thanks for taking the time to report this issue

I've a pull request coming in where we change the render level which may affect this issue

Please review the tests here: https://github.com/rosscdh/mkdocs-markdownextradata-plugin/pull/20/files

where you will see ive taken your specific case and integrated it. 

As the tests there are green please retry when that PR merges
