### ISSUE TITLE
Issues with prebuilt search index and nav

### ISSUE THREAD

**Issue by miffels** [rosscdh/mkdocs-markdownextradata-plugin#19]
Hey,

Thanks for providing the plugin! Alas, I noticed a few edge cases in which it doesn't integrate nicely with `mkdocs` (or more specifically with `mkdocs-material`:

1. It appears that mkdocs picks up the page titles before the markdown is processed by Jinja, which leads to page titles containing placeholders in the output. E.g., when you have a page like

    ```markdown
    # Title with {{ placeholder }}
    ```

    The plugin will replace the value in the page body, but the page title in the browser and in the nav will still say "Title with {{ placeholder }}"
    It appears to me that the ToC needs to be transformed in addition to the body.

1. I've seen some possibly quirks with the search - say `{{ placeholder }}` resolves to "Placeholder", when I search for "Title with Placeholder" the search won't be able to find the page. This may not actually be true in this rather simple case, but seems to apply in our cases where we have `more.complex.placeholder.variables`.

**Comment by rosscdh** [comment]
Nice catches! and thank you for the PR! I really appreciate it!
