### ISSUE TITLE
python is difficult

### ISSUE THREAD

**Issue by snelweg** [rosscdh/mkdocs-markdownextradata-plugin#2]
Collecting mkdocs-markdownextradata-plugin
  Could not find a version that satisfies the requirement mkdocs-markdownextradata-plugin (from versions: )
No matching distribution found for mkdocs-markdownextradata-plugin

What does this mean ???????

> mkdocs --version
mkdocs, version 1.0 from /usr/local/lib/python2.7/dist-packages/mkdocs (Python 2.7)

>python --version
Python 2.7.13

**Comment by rosscdh** [comment]
Hey there,

Python 3 only I believe

**Comment by rosscdh** [comment]
https://github.com/rosscdh/mkdocs-markdownextradata-plugin/blob/master/setup.py#L29

**Comment by rosscdh** [comment]
just uploaded 0.0.5 try pip install the plugin again with -U

```
pip install mkdocs-markdownextradata-plugin==0.0.5
```

**Comment by snelweg** [comment]
> just uploaded 0.0.5 try pip install the plugin again with -U

Thanks, it works now!
Keep up the good work, thank you for making this available!

**Comment by rosscdh** [comment]
My pleasure mate. Good luck with your project and thanks for helping refine
it.
