### ISSUE TITLE
Plugin parses ```raw code

### ISSUE THREAD

**Issue by pedromorgan** [rosscdh/mkdocs-markdownextradata-plugin#21]
It appears that this plugins tries to parse stuff in ```raw``` tags

eg this "OverPass query"

https://gitlab.com/fizzy-knitting/fizzy-knitting.gitlab.io/edit/master/docs/overpass-query.md

Expected is to ignore code tags... or am I missing something ?

**Comment by rosscdh** [comment]
I've reverted and released 0.1.7 https://pypi.org/project/mkdocs-markdownextradata-plugin/ see if that works for you

**Comment by SimonMarquis** [comment]
Unfortunately, this is still an issue on the latest version (0.2.5).
