### ISSUE TITLE
Feature request: allow generating dynamic number of pages

### ISSUE THREAD

**Issue by vlcinsky** [rosscdh/mkdocs-markdownextradata-plugin#25]
We use MkDocs for generating content of [Czech National Traffic Information Registry](http://registr.dopravniinfo.cz/en/sources/).

There is one large yaml file, which defines all sources, formats, providers etc.

Currently, we have pre-processing step (based on [doit](https://pydoit.org/)) which takes care of generating dynamic number of pages - one per specific source, format, provider etc.

The `mkdocs-markdownextradata-plugin` would serve excellently to generate "index pages" such as [list of sources](http://registr.dopravniinfo.cz/en/sources/), [formats](http://registr.dopravniinfo.cz/en/formats/), [protocols](http://registr.dopravniinfo.cz/en/protocols/) etc.

I see, there is currently no option to use this plugin to generate dynamic number of pages, such as [Source: DATEX II Situation Publication - Common](http://registr.dopravniinfo.cz/en/sources/cz-ndic_d2-common/). If we would have such option, we could simplify site generation and get rid of doit pre-processing.

Do you think, there is an option to extend this plugin to allow that?

**Comment by miffels** [comment]
I am not maintaining this plugin, but it appears to me that this is somewhat out of scope. However, it is easy enough to write your own MkDocs plugin and is the path I have chosen for other custom processing that I require for my documentation. Maybe that is something that might work for you? Otherwise, feel free to elaborate on why and how this would fit into this plugin specifically.

**Comment by vlcinsky** [comment]
Thanks @miffels for your hints.

As soon as we will have to update our project generating the Czech National Traffic Information Registry, I will considering to change the doit pre-processing using MkDocs plugin as you suggest.

If things go well, we might either provide it as contribution to this plugin or release a new one.

I would put a note about our results in this issue.
