### ISSUE TITLE
Pypi-Release

### ISSUE THREAD

**Issue by miffels** [rosscdh/mkdocs-markdownextradata-plugin#30]
Hey,

I noticed the last changes haven't yet made it onto Pypi: The latest version there still is `0.1.7` although the tags are already at `0.1.9`. Would it be possible for you to update the package, please?

Thanks!

**Comment by rosscdh** [comment]
Thanks for the bump! now available https://pypi.org/project/mkdocs-markdownextradata-plugin/

**Comment by miffels** [comment]
Thank you :)
