### ISSUE TITLE
How to export all the MD files

### ISSUE THREAD

**Issue by ShivKJ** [rosscdh/mkdocs-markdownextradata-plugin#36]
Hi there,

I have started to learn Mkdocs and got to know that we can inject variables in `.md` using this plugin.

So with the help of this plugin, we can configure the documentation better.

I was wondering if we can export all the modified markdown files (markdown files after injection of variables defined in `extra`)

**Comment by rosscdh** [comment]
```
wget \
     --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --no-parent \
         localhost:8000
```
