### ISSUE TITLE
Bug when using `mkdocs serve -f` 

### ISSUE THREAD

**Issue by timvink** [rosscdh/mkdocs-markdownextradata-plugin#37]
I ran into a bug when using `mkdocs serve` (and `mkdocs build`) from another directory than the `mkdocs.yml` file.\

Reproducable example here: https://github.com/timvink/bugreportexample

**Comment by rosscdh** [comment]
try absolute path

```
site_name: My Docs

plugins:
    - search
    - markdownextradata:
        data: /tmp/bugreportexample/{{ cookiecutter.reponame }}/docs/assets
```


```
❯ mkdocs serve -f \{\{\ cookiecutter.reponame\ \}\}/mkdocs.yml
INFO     -  Building documentation...
INFO     -  Cleaning site directory
INFO     -  Documentation built in 0.05 seconds
INFO     -  [21:08:44] Serving on http://127.0.0.1:8000/

```

**Comment by rosscdh** [comment]
```
site_name: My Docs

plugins:
    - search
    - markdownextradata:
        data: ./{{ cookiecutter.reponame }}/docs/assets
```

also works

**Comment by rosscdh** [comment]
I've updated the package to assume config path

https://github.com/rosscdh/mkdocs-markdownextradata-plugin/commit/24492bc6df7dbc58b17ab7aabb80acf0d10e7e5d

can you pip install -e at latest.. and if it works then ill make a release

**Comment by timvink** [comment]
Works 🌟 

Thanks! That's a couple less users having to find a workaround :)

**Comment by rosscdh** [comment]
released https://pypi.org/project/mkdocs-markdownextradata-plugin/0.2.5/
