### ISSUE TITLE
DeprecationWarning: warning_filter

### ISSUE THREAD

**Issue by devajmeireles** [rosscdh/mkdocs-markdownextradata-plugin#47]
I get this error when I try to build doc, macOS 13.4.1:

![CleanShot 2023-08-03 at 1 12 43](https://github.com/rosscdh/mkdocs-markdownextradata-plugin/assets/60591772/386f8b93-50f2-4f6f-8550-72786dda9fe9)

**Comment by tiangolo** [comment]
I was able to replace `mkdocs-mardkownextradata-plugin` with `mkdocs-macros-plugin` for FastAPI in this PR https://github.com/tiangolo/fastapi/pull/11383
