### ISSUE TITLE
event is undefined caused by event() in snippet

### ISSUE THREAD

**Issue by agardnerIT** [rosscdh/mkdocs-markdownextradata-plugin#52]
```shell
now-{{ event()['duration']}}
```

This snippet is causing an exception...

```
jinja2.exceptions.UndefinedError: 'event' is undefined
```

**Comment by agardnerIT** [comment]
For anyone else the issue is the `{{` which are being interpreted by jinja.

Fix is to surround the block with `{% raw %}` and  `{% endraw %}` like this:

```
{% raw %}
```
now-{{ event()['duration'] }}
```
{% endraw %}
```

**Comment by rosscdh** [comment]
Well done 👍
